<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ SPDX-FileCopyrightText: 2025 Zextras <https://www.zextras.com>
  ~
  ~ SPDX-License-Identifier: AGPL-3.0-only
  -->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.zextras</groupId>
    <artifactId>mailbox-attribute-manager-parent</artifactId>
    <version>${revision}${changelist}</version>
  </parent>

  <artifactId>zattr</artifactId>
  <packaging>jar</packaging>

  <dependencies>
    <dependency>
      <groupId>com.zextras</groupId>
      <artifactId>mailbox-attribute-manager</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>add-zattr-source</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>${generated-zattr}</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>generate-ZAttrProvisioning</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>com.zimbra.cs.account.AttributeManagerUtil</mainClass>
              <arguments>
                <argument>-a</argument>
                <argument>generateProvisioning</argument>
                <argument>-r</argument>
                <argument>${generated-zattr}/ZAttrProvisioning.java</argument>
              </arguments>
            </configuration>
          </execution>
          <execution>
            <id>generate-ZAttrAccount</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>com.zimbra.cs.account.AttributeManagerUtil</mainClass>
              <arguments>
                <argument>-a</argument>
                <argument>generateGetters</argument>
                <argument>-c</argument>
                <argument>account</argument>
                <argument>-r</argument>
                <argument>${generated-zattr}/ZAttrAccount.java</argument>
              </arguments>
            </configuration>
          </execution>
          <execution>
            <id>generate-ZAttrCalendarResource</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>com.zimbra.cs.account.AttributeManagerUtil</mainClass>
              <arguments>
                <argument>-a</argument>
                <argument>generateGetters</argument>
                <argument>-c</argument>
                <argument>calendarResource</argument>
                <argument>-r</argument>
                <argument>${generated-zattr}/ZAttrCalendarResource.java</argument>
              </arguments>
            </configuration>
          </execution>
          <execution>
            <id>generate-ZAttrConfig</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>com.zimbra.cs.account.AttributeManagerUtil</mainClass>
              <arguments>
                <argument>-a</argument>
                <argument>generateGetters</argument>
                <argument>-c</argument>
                <argument>globalConfig</argument>
                <argument>-r</argument>
                <argument>${generated-zattr}/ZAttrConfig.java</argument>
              </arguments>
            </configuration>
          </execution>
          <execution>
            <id>generate-ZAttrCos</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>com.zimbra.cs.account.AttributeManagerUtil</mainClass>
              <arguments>
                <argument>-a</argument>
                <argument>generateGetters</argument>
                <argument>-c</argument>
                <argument>cos</argument>
                <argument>-r</argument>
                <argument>${generated-zattr}/ZAttrCos.java</argument>
              </arguments>
            </configuration>
          </execution>
          <execution>
            <id>generate-ZAttrDistributionList</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>com.zimbra.cs.account.AttributeManagerUtil</mainClass>
              <arguments>
                <argument>-a</argument>
                <argument>generateGetters</argument>
                <argument>-c</argument>
                <argument>distributionList</argument>
                <argument>-r</argument>
                <argument>${generated-zattr}/ZAttrDistributionList.java</argument>
              </arguments>
            </configuration>
          </execution>
          <execution>
            <id>generate-ZAttrDomain</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>com.zimbra.cs.account.AttributeManagerUtil</mainClass>
              <arguments>
                <argument>-a</argument>
                <argument>generateGetters</argument>
                <argument>-c</argument>
                <argument>domain</argument>
                <argument>-r</argument>
                <argument>${generated-zattr}/ZAttrDomain.java</argument>
              </arguments>
            </configuration>
          </execution>
          <execution>
            <id>generate-ZAttrDynamicGroup</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>com.zimbra.cs.account.AttributeManagerUtil</mainClass>
              <arguments>
                <argument>-a</argument>
                <argument>generateGetters</argument>
                <argument>-c</argument>
                <argument>group</argument>
                <argument>-r</argument>
                <argument>${generated-zattr}/ZAttrDynamicGroup.java</argument>
              </arguments>
            </configuration>
          </execution>
          <execution>
            <id>generate-ZAttrServer</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>com.zimbra.cs.account.AttributeManagerUtil</mainClass>
              <arguments>
                <argument>-a</argument>
                <argument>generateGetters</argument>
                <argument>-c</argument>
                <argument>server</argument>
                <argument>-r</argument>
                <argument>${generated-zattr}/ZAttrServer.java</argument>
              </arguments>
            </configuration>
          </execution>
          <execution>
            <id>generate-ZAttrShareLocator</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>com.zimbra.cs.account.AttributeManagerUtil</mainClass>
              <arguments>
                <argument>-a</argument>
                <argument>generateGetters</argument>
                <argument>-c</argument>
                <argument>shareLocator</argument>
                <argument>-r</argument>
                <argument>${generated-zattr}/ZAttrShareLocator.java</argument>
              </arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <properties>
    <generated-zattr>${project.build.directory}/generated-sources/zattr</generated-zattr>
  </properties>
</project>
